name: Anuj CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  APP_NAME: myapp
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Hello"

  deploy:
    needs: build
  #  if: github.ref == 'refs/heads/dev'
    if: success()
    runs-on: ubuntu-latest
  #  environment: production

    steps:
      - run: echo "Hi"

      - run: |
          echo "APP: $APP_NAME"
          echo "Region: $AWS_REGION"

      - run: |
          echo "Secret exists"
        env:
          SECRET: ${{ secrets.ABC }}

      - run: |
          echo "Var: $REPOSITORY_VAR"
        env:
          REPOSITORY_VAR: ${{ vars.XYZ }}